### ISSUE TITLE
Google Cloud Storage enumeration options are missing options

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#19]
The fields "location" and "storage class" are strings, but there are a a number of presets available:

<img width="571" alt="Screenshot 2024-10-28 at 13 54 13" src="https://github.com/user-attachments/assets/0e776775-bf7d-4bdd-9d1a-868c8fe43c9d">

The presets are part of the option's list of possible values.
The user should be able to type a custom string, or pick one of the values.

Here is the previous UI for inspiration:
<img width="697" alt="Screenshot 2024-10-28 at 13 54 02" src="https://github.com/user-attachments/assets/c17da27e-fae5-419f-a9df-4b27602a98db">

**Comment by sp90** [comment]
It should just be sent as an enumeration with `ValidValues` from the backend that way it's handled correctly in the frontend automagically 👍

**Comment by kenkendk** [comment]
The challenge here is that it is not an enumeration. It is a free-text field.
The WebModule returns a dictionary with (label, key) pairs for the most common options.

**Comment by sp90** [comment]
Then we should maybe have a "suggested options" kind of field so we can feed in the data in the same way
