### ISSUE TITLE
The SSH page advanced option SSH keyfile could use a browse dialog

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#29]
Since there already exists a browse dialog, maybe we could reuse it to allow the user to pick the file?

**Comment by sp90** [comment]
Please elaborate how we could do this?

**Comment by sp90** [comment]
@kenkendk what file type is it we're accepting into this field?

**Comment by kenkendk** [comment]
Technically it is a text file with the private key.
But the extensions vary:
https://superuser.com/questions/1515261/how-to-quickly-identify-ssh-private-key-file-formats

I guess for this, we could also consider that the user uploads a private key from their local machine and we encode it?

**Comment by sp90** [comment]
Well we could allow all the file formats mentioned above + txt 

How would this play along with remote control?

Would it be better with the file upload field?

**Comment by kenkendk** [comment]
For the file upload, my idea was that the person setting it up has the key on their local machine somehow. They can then upload it and it will be stored in the settings database (hopefully encrypted) and they do not need the keyfile to be present in the filesystem on the machine running Duplicati.

The other situation is where the SSH key is needed for other purposes than Duplicati. Here it may make sense to simply point to the keyfile, and then some other process will make sure the key is rotated etc.

**Comment by sp90** [comment]
If we should upload it the API needs to support uploading files and passing them on where the file finder is much easier for now just selecting where on the machine it lives

**Comment by kenkendk** [comment]
For uploading, we should use the native file upload and then set the option `--ssh-key=<contents-of-file>`.
This is mutually exclusive with the `--ssh-keyfile` option.
