### ISSUE TITLE
Backends should have a way to view and insert the url

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#31]
The url generated by the backend editor should be copy-able (and view-able) by the user.
Also, the user should be able to paste in a previously saved url.

**Comment by sp90** [comment]
So it's fairly easy to just add the field where you can add a URL but it would overwrite all of what has been added to the current backup would we be happy with that or should the user be presented with a dialog where they can accept before moving on?

**Comment by kenkendk** [comment]
I would say that entering a URL is a pretty advanced action. If a user is advanced enough to insert a URL we should assume they understand the risks. If the UI looks messed up they can always choose not to save it.
