### ISSUE TITLE
Source page changes needed

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#35]
Managing filters to get it "just right" can be time consuming.
We should have some way of letting the user see the effects of their choices.

One way could be to show the folder tree but let the BE apply the filters.
The BE supports full trace of this so it can report exactly what rule made a folder be included or excluded.
If the user can browse the source folders with filters enabled and have a visual feedback of what filters are applied, it becomes less error prone to adjust the filters.

This may need a new BE endpoint to support getting the detailed information to the FE.

#### Closed tickets about the same page

#34 - On the source folder page, it should be possible to add and remove filters.

#33 - It is a bit hard to figure out what is actually selected with the current color scheme.
The previous editor was using tri-state checkboxes where indeterminate state was used to indicate a partial selection of the folder.

We could also split the view into two operations:

Select source folders (don't show children of selected parents)
Adjust selection with filters/removal
The two steps are internally different as (1) results in source paths and (2) results in filters.

#32 - The source folder view should have some way of being edited as text.
The purpose of this is to both have a simpler way of choosing multiple folder, but also a way to select folders that may not be browse-able.

**Comment by sp90** [comment]
@kenkendk Could you be more specific on what the user wanna see?

**Comment by sp90** [comment]
#34 and #33 seems like all these should be bundled together and defined the best experience possible

**Comment by sp90** [comment]
Same goes for #32

**Comment by sp90** [comment]
I will close the other issues in favor of this one issue and copy over the content to this one, we had an internal meeting about it and we're about to design a more general solution for it.
