### ISSUE TITLE
Improved advanced options usability

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#39]
The options that are timespans should be configureable with:
- a number
- a multiplier (seconds, minutes, hours, days, weeks, months)

The options that are sizes should be configureable with:
- a number
- a multiplier (byte, kb, mb, gb, tb, pb)

The options that are enumerations should be configureable with:
- a dropdown with the options

The options that are strings and have values should be configurable with:
- a text field
- a dropdown with options

The options that are modules should behave as enumerations (compression-module, encryption-module).
The options "enable-module" and "disable-module" should use the list of generic modules.

<img width="532" alt="Screenshot 2024-10-28 at 15 53 19" src="https://github.com/user-attachments/assets/f56d4f10-558a-48be-bdf4-651f62faee05">

**Comment by sp90** [comment]
This needs to be handled similarly to the options on the destination page - I will add it
