### ISSUE TITLE
Add loader to all backend operations

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#46]
If operations are transmitted through the console there can be a significant delay.
To avoid confusion it makes sense to add spinner/loader whenever activating a backend operation.

**Comment by sp90** [comment]
Fixed for submitting on backups

**Comment by sp90** [comment]
Fixed for 
- Restore submit
- Backup submit
- Backups list 
- Restores list
- File tree 
- Logging out 
- Importing config
