### ISSUE TITLE
When iCloud Password manager extension is active in Chrome, it obscures the encryption method fields.

### ISSUE THREAD

**Issue by kenkendk** [duplicati/ngclient#7]
On the add/edit backup page where the encryption method is chosen, it triggers as a password field, which obscures the dropdown:
<img width="556" alt="Screenshot 2024-10-28 at 13 20 58" src="https://github.com/user-attachments/assets/22990d55-8be8-48c5-862f-50cd30b54d55">

**Comment by sp90** [comment]
Fixed
